# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/